layout_spectrum: 0.15775658272870696
typography_spectrum: 0.7782328783896854
color:
  brandStrength: 0.3895303689387839
  lightness: 0.9704173895657653
  saturation: 0.1259953596890157
  rhythmicContrast: 0.7288031567393405
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: sostool
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://dl.dropboxusercontent.com/content_link/e1BzdD9ocR2lV2QLMORYS6zDtoTJbGm2lg7V4YAhUQeNP6J2e1aUN8qk3iVSfR1g/file?dl=0&duc_id=UzBomG852tqmx84DAud4wxeqrAQyF6NenNpkSspzvmOWM9BGuf6A8nK09v4TklkZ&raw=1&size_mode=5">
    src: >-
      https://dl.dropboxusercontent.com/content_link/e1BzdD9ocR2lV2QLMORYS6zDtoTJbGm2lg7V4YAhUQeNP6J2e1aUN8qk3iVSfR1g/file?dl=0&duc_id=UzBomG852tqmx84DAud4wxeqrAQyF6NenNpkSspzvmOWM9BGuf6A8nK09v4TklkZ&raw=1&size_mode=5
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://dl.dropboxusercontent.com'
        name: Dropboxusercontent
        favicon: null
        domain: dl.dropboxusercontent.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://dl.dropboxusercontent.com/content_link/e1BzdD9ocR2lV2QLMORYS6zDtoTJbGm2lg7V4YAhUQeNP6J2e1aUN8qk3iVSfR1g/file?dl=0&duc_id=UzBomG852tqmx84DAud4wxeqrAQyF6NenNpkSspzvmOWM9BGuf6A8nK09v4TklkZ&raw=1&size_mode=5
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: SoS TooL
description: "Here you can find useful #tools. #Survival #Mechanical #Cooking...the most needed \uD83C\uDD98#tool.\uD83D\uDEE0Free world wide shipping"
author:
  url: 'http://sostool.help/'
  name: SoS TooL
  email: sostool.help@gmail.com
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab597c8f-072e-472a-b388-3f102f2656fb.jpg
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/19414101-96f1-4aa0-8e28-8a13ea79c22e.jpg
purpose:
  - type: contact
    url: 'mailto:sostool.help@gmail.com'
    label: 'Contact us : sostool.help@gmail.com'
analytics:
  google: '102001020'
