typography_spectrum: 0.7782328783896854
color:
  brandStrength: 0.3895303689387839
  lightness: 0.9704173895657653
  saturation: 0.1259953596890157
  rhythmicContrast: 0.7288031567393405
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
layout_spectrum: 0.15775658272870696
analytics:
  google: UA-102001020-1
  twitter: '@sosTooL_Help'
author:
  url: 'http://sostool.help/'
  name: SoS TooL
  email: sostool.help@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab597c8f-072e-472a-b388-3f102f2656fb.jpg
name: sostool
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    id: 913ae59a-5283-4c91-9891-946408071787
    type: content
  - name: Privacy policies
    id: a626a255-56f6-4166-b5d4-acb5b585b381
    type: content
  - name: Shipping terms
    id: e7ee4dbe-c62a-4aa9-ad77-d9508bec3949
    type: content
  - name: Payment methods
    id: 7543d2bd-41a4-4546-af97-6a10e489c8e7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/19414101-96f1-4aa0-8e28-8a13ea79c22e.jpg
title: SoS TooL
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://dl.dropboxusercontent.com/content_link/e1BzdD9ocR2lV2QLMORYS6zDtoTJbGm2lg7V4YAhUQeNP6J2e1aUN8qk3iVSfR1g/file?dl=0&duc_id=UzBomG852tqmx84DAud4wxeqrAQyF6NenNpkSspzvmOWM9BGuf6A8nK09v4TklkZ&raw=1&size_mode=5">
    src: >-
      https://dl.dropboxusercontent.com/content_link/e1BzdD9ocR2lV2QLMORYS6zDtoTJbGm2lg7V4YAhUQeNP6J2e1aUN8qk3iVSfR1g/file?dl=0&duc_id=UzBomG852tqmx84DAud4wxeqrAQyF6NenNpkSspzvmOWM9BGuf6A8nK09v4TklkZ&raw=1&size_mode=5
    metadata:
      datePublished: null
      isBasedOnUrl: >-
        https://dl.dropboxusercontent.com/content_link/e1BzdD9ocR2lV2QLMORYS6zDtoTJbGm2lg7V4YAhUQeNP6J2e1aUN8qk3iVSfR1g/file?dl=0&duc_id=UzBomG852tqmx84DAud4wxeqrAQyF6NenNpkSspzvmOWM9BGuf6A8nK09v4TklkZ&raw=1&size_mode=5
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://dl.dropboxusercontent.com'
        name: Dropboxusercontent
        favicon: null
        domain: dl.dropboxusercontent.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: "Here you can find the best ever innovative \uD83C\uDD98#tools. #Survival #Mechanical #Cooking...Ho also anti-stress anxiety relief fidget spinners!\uD83D\uDEE0Free worldwide shipping"
purpose:
  - type: contact
    url: 'mailto:sostool.help@gmail.com'
    label: 'Contact us : sostool.help@gmail.com'
github: true
